# 3. High correlation between two columns

what is High correlation?
> High correlation between two variables means they have similar trends and are likely to carry similar information.

How it's work.
1. Basically,calculate the correlation between independent numerical variables that are numerical in nature.
2. Then If the correlation coefficient crosses a certain threshold value, we can drop one of the variables.

In [97]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [114]:
df=pd.read_csv('travel-times.csv')
df

,Date,StartTime,DayOfWeek,GoingTo,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,FuelEconomy,TotalTime,MovingTime,Take407All,Comments
0,1/6/2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,1/6/2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,1/4/2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
3,1/4/2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,NaN
4,1/3/2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No,NaN
201,7/14/2011,08:03,Thursday,GSK,50.90,123.7,76.2,95.1,7.89,40.1,32.1,Yes,NaN
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,76.7,NaN,54.2,40.6,Yes,NaN
203,7/12/2011,17:51,Tuesday,Home,53.28,125.8,61.6,87.6,NaN,51.9,36.5,Yes,NaN
204,7/11/2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,NaN

In [115]:
# Check correlation  beteeen columns
cor_matrix = df.corr().abs()
cor_matrix

,Distance,MaxSpeed,AvgSpeed,AvgMovingSpeed,TotalTime,MovingTime
Distance,1.000000,0.145091,0.006445,0.011874,0.197207,0.197044
MaxSpeed,0.145091,1.000000,0.253869,0.257823,0.198775,0.222574
AvgSpeed,0.006445,0.253869,1.000000,0.872143,0.877806,0.835814
AvgMovingSpeed,0.011874,0.257823,0.872143,1.000000,0.856986,0.944433
TotalTime,0.197207,0.198775,0.877806,0.856986,1.000000,0.920935
MovingTime,0.197044,0.222574,0.835814,0.944433,0.920935,1.000000

In [116]:
# corresponding correlation
upper_tri = cor_matrix.where(np.triu(np.ones(cor_matrix.shape),k=1).astype(np.bool))
print(upper_tri)

                Distance  MaxSpeed  AvgSpeed  AvgMovingSpeed  TotalTime  \
Distance             NaN  0.145091  0.006445        0.011874   0.197207
MaxSpeed             NaN       NaN  0.253869        0.257823   0.198775
AvgSpeed             NaN       NaN       NaN        0.872143   0.877806
AvgMovingSpeed       NaN       NaN       NaN             NaN   0.856986
TotalTime            NaN       NaN       NaN             NaN        NaN
MovingTime           NaN       NaN       NaN             NaN        NaN

                MovingTime
Distance          0.197044
MaxSpeed          0.222574
AvgSpeed          0.835814
AvgMovingSpeed    0.944433
TotalTime         0.920935
MovingTime             NaN

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.

In [108]:
# check correlation in variable  and if morethen 0.9% then romove ehos variable
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.90)]
print(to_drop)

['MovingTime']