## type of data

Basically in reallife we have two type of data
1. catagorical data
2. numerical data

what is catagorical data?
> Categorical data refers to a data type that can be stored and identified based on the names or labels given to them.
well data can be visulazed by using Bar Plot, Pie Chart, Pareto Chart.

what is numerical data?
> Numerical data refers to the data that is in the form of numbers, and not in any language or descriptive form.
well data can be visulazed by using Histogram, Line Plot, Scatter Plot.

Before analyze data we have to check selected data is population or sample dataset.

Population Data:
> Means during analsis all data will analyze **ex** 1) Election result

Sample Data:
> Select only few random data well size of the sample is always less than the total size of the population data.
**ex** 1) Election exit poll

Let's talk about measures of data.
1. Central Tendency
2. Asymmetry
3. Variability(Dispersion)
4. Quartiles
5. Relationship
6. Standard Deviation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('cereal.csv')
df

,Cereal Name,Manufacturer,Type,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
0,100%_Bran,Nabisco,C,70,4,1,130,10.0,5.0,6,3,280,25,1.0,0.33
1,100%_Natural_Bran,Quaker Oats,C,120,3,5,15,2.0,8.0,8,3,135,0,1.0,-1.00
2,All-Bran,Kelloggs,C,70,4,1,260,9.0,7.0,5,3,320,25,1.0,0.33
3,All-Bran_with_Extra_Fiber,Kelloggs,C,50,4,0,140,14.0,8.0,0,3,330,25,1.0,0.50
4,Almond_Delight,Ralston Purina,C,110,2,2,200,1.0,14.0,8,3,-1,25,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,General Mills,C,110,2,1,250,0.0,21.0,3,3,60,25,1.0,0.75
70,Trix,General Mills,C,110,1,1,140,0.0,13.0,12,2,25,25,1.0,1.00
71,Wheat_Chex,Ralston Purina,C,100,3,1,230,3.0,17.0,3,1,115,25,1.0,0.67
72,Wheaties,General Mills,C,100,3,1,200,3.0,17.0,3,1,110,25,1.0,1.00
73,Wheaties_Honey_Gold,General Mills,C,110,2,1,200,1.0,16.0,8,1,60,25,1.0,0.75

In [5]:
# Central Tendency
Mean = int(df['Potassium'].mean())
Median =int(df['Potassium'].median())
Mode =df['Potassium'].mode()

print("Mean :",Mean)
print("Median :",Median)
print("Mode:",Mode[0])

Mean : 92
Median : 90
Mode: 35

In [7]:
# Asymmetry
# Positive Skewness: Positive Skewness is when the mean>median>mode.
# Negative Skewness: Negative Skewness is when the mean<median<mode.
if  Mean>Median>int(Mode[0]):
  print("Positive Skewness")
elif Mean<Median<int(Mode[0]):
  print('Negative Skewness')
else:
  print("nothing")

Positive Skewness

In [8]:
#Variability(Dispersion)
Range=max(df['Calories'])-min(df['Calories'])
print("Range value is :",Range)

Range value is : 110